import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Link } from "react-router-dom";
import Hero from "../components/HeroPremium";
import SectionTitle from "../components/SectionTitle";
import ServiceCard from "../components/ServiceCard";
import Stats from "../components/Stats";
import Industries from "../components/Industries";
import Testimonials from "../components/Testimonials";
import CTA from "../components/CTA";
import { services, whyUs } from "../data/content";
export default function HomeCorporate() { return <><Hero /><section className="section intro corporate-intro"><div className="container corporate-intro-grid"><div className="corporate-intro-title"><span className="eyebrow">Workforce & Operations</span><h2>People, processes and site operations working together.</h2><p>Fescora Management provides practical workforce and facility solutions for businesses that need dependable people, disciplined execution and clearer operational coordination.</p></div><div className="corporate-intro-content"><p className="lead">From security and housekeeping to manpower outsourcing and workforce support, we help organisations manage essential operations with a structured, service-focused approach.</p><div className="expertise-grid"><article><span>Security & Facility Services</span><p>Professional teams for security, housekeeping and day-to-day facility support, aligned to the requirements of each site.</p></article><article><span>Manpower & Workforce Support</span><p>Skilled, semi-skilled and support manpower solutions designed around operational requirements, workforce continuity and site needs.</p></article></div><Link className="text-link red" to="/about">Learn More About Fescora <ArrowRight size={17} /></Link></div></div></section><section className="section service-section"><div className="container"><SectionTitle eyebrow="Our Services" title="Practical workforce and facility solutions." text="From frontline site services to workforce administration and HR support, Fescora brings essential operational requirements together under one service partner."/><div className="service-grid">{services.map((s, i) => <ServiceCard service={s} index={i} key={s[0]} />)}</div><Link className="text-link red view-all" to="/services">Explore service details <ArrowRight size={17} /></Link></div></section><Stats /><section className="section advantage-section"><div className="container"><div className="advantage-intro"><SectionTitle eyebrow="Why Fescora" title="A dependable partner for essential operations."/><p>Managing people and facilities requires consistency. Fescora focuses on dependable service teams, clear processes and responsive coordination so businesses can stay focused on their core operations.</p></div><div className="advantage-grid">{whyUs.map(([title, text], i) => <article key={title}><div><CheckCircle2 size={20} /><b>0{i + 1}</b></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><Industries /><Testimonials /><CTA /></> }