import LegalPage from '../components/LegalPage'
const sections = [
  { heading: 'Information We Collect', paragraphs: ['We may collect information you provide through contact enquiries, career applications and candidate registration forms. This may include contact details, employment, qualification and experience information, and other information relevant to your enquiry or profile.'] },
  { heading: 'Payment-Related Information', paragraphs: ['Candidate registration payments are processed through the payment gateway used on this website. Fescora Management does not intend to store complete card, bank or other payment-instrument details. We may retain payment confirmation, transaction reference and registration details needed to administer a registration.'] },
  { heading: 'How We Use Information', paragraphs: ['Information may be used to respond to enquiries, review candidate profiles, administer registrations, communicate about relevant services or opportunities, maintain records, improve website operations and meet applicable operational requirements.'] },
  { heading: 'Email Communication', paragraphs: ['We may use the email address you provide to send responses, registration confirmations and communications relevant to your enquiry or candidate profile.'] },
  { heading: 'Service Providers and Third Parties', paragraphs: ['We may use service providers, including payment processors, email providers and website hosting providers, to operate the website and deliver related services. Such providers may process information only as needed to provide their services.'] },
  { heading: 'Cookies and Analytics', paragraphs: ['This website may use essential technical tools and, where enabled, analytics tools to understand website use and improve performance. You can manage cookies through your browser settings.'] },
  { heading: 'Data Security and Retention', paragraphs: ['We take reasonable steps to protect information handled through this website. Information is retained only for as long as reasonably necessary for the purposes described here, operational record-keeping or applicable requirements.'] },
  { heading: 'Your Rights and Contact', paragraphs: ['To ask about your personal information, request a correction or raise a privacy concern, contact [Fescora Management official contact details].'] },
  { heading: 'Children\'s Privacy', paragraphs: ['This website is not intended to knowingly collect personal information from children. If you believe such information has been provided, contact [Fescora Management official contact details].'] },
  { heading: 'Updates to This Policy', paragraphs: ['This policy may be updated from time to time. The version published on this website will apply from the date it is posted.'] },
]
export default function PrivacyPolicy() { return <LegalPage eyebrow="Privacy Policy" title="Privacy Policy" intro="How Fescora Management handles information shared through this website." sections={sections} /> }